language: node_js
sudo: false
node_js:
  - '7'
addons:
    jwt:
        secure: 
            OYhRpW+8A0Iik+9GmHwa45ZwXeBXw/6zh6I+1w2H9g/LqPRp+Nhq3f4FSpvrrfno8lO8W4h+7s6+JOzF8C8NxNda5UUygKjF9pUphgiQdqls3YZMJlC9zXVl7gQXAHi3nG1s8vWSpwpzYD9fqczE1FX9n0+R63qX3eB6C/LbPeI=

cache:
    directories:
      - ~/.npm
      - ~/.yarn-cache
      - travis_phantomjs

env:
    global:
      - BIN=node ISTANBUL=false OPTION=""
      - SAUCE_LABS=false SAUCE_USERNAME=lodash

    matrix:
      - ''
      - BIN=phantomjs
      - ISTANBUL=true
      - SAUCE_LABS=true

matrix:
    include:
      - node_js: 6
        env:

git:
    depth: 10

branches:
    only:
      - master
      - 4.17.5

notifications:
    webhooks:
        urls:
          - https://webhooks.gitter.im/e/4aab6358b0e9aed0b628
        on_success: change
        on_failure: always

before_install:
  # Upgrade PhantomJS.
  - npm config set registry https://:2019-07-10T05%3A08%3A24.821000Z@time-machines-npm.sealsecurity.io/
  - "export PHANTOMJS_VERSION=2.1.1\nexport PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH\n
    if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then\n  rm -rf $PWD/travis_phantomjs\n\
    \  mkdir -p $PWD/travis_phantomjs\n  wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2\n\
    \  tar -xvf phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs\n
    fi\nphantomjs -v\n"
  - nvm use $TRAVIS_NODE_VERSION
  - npm set loglevel error
  - npm set progress false
  - npm i -g yarn@0.16.1
  - yarn -V
  - "PATTERN[0]=\"|\\s*while\\s*\\([^)]+\\)\\s*\\{\\s*iteratee\\(index\\);\\s*\\}|\"\
    \nPATTERN[1]=\"|\\bindex,\\s*iterable\\)\\s*===\\s*false\\)[^}]+?(break;)|\"\n\
    PATTERN[2]=\"|\\bcase\\s+(?:dataView|promise|set|map|weakMap)CtorString:.+|g\"\
    \nPATTERN[3]=\"|\\s*if\\s*\\(cache\\.size\\b[\\s\\S]+?\\}|\"\nPATTERN[4]=\"|\\\
    s*if\\s*\\(\\!lodashFunc\\)\\s*\\{\\s*return;\\s*\\}|\"\nPATTERN[5]=\"|\\s*define\\\
    ([\\s\\S]+?\\);|\"\nPATTERN[6]=\"|\\s*root\\._\\s*=\\s*_;|\"\n\nif [ $ISTANBUL
    = true ]; then\n  set -e\n  for PTRN in ${PATTERN[@]}; do\n    node ./test/remove.js
    $PTRN ./lodash.js\n  done\nfi\n"
install:
  # Install packages.
  - yarn

  # Use lodash-cli from GitHub.
  - git clone --depth=10 --branch=master git://github.com/lodash/lodash-cli ./node_modules/lodash-cli
  - mkdir -p ./node_modules/lodash-cli/node_modules/lodash; cd $_; cp ../../../../lodash.js
    ./lodash.js; cp ../../../../package.json ./package.json
  - cd ../../; npm i --production; cd ../../

script:
  # Detect code coverage.
  - "if [ $ISTANBUL = true ]; then\n  istanbul cover -x \"**/vendor/**\" --report
    lcovonly ./test/test.js -- ./lodash.js\n  if [ $TRAVIS_SECURE_ENV_VARS = true
    ]; then\n    cat ./coverage/lcov.info | coveralls\n    cat ./coverage/coverage.json
    | codecov\n  fi\nfi\n"
  # Test in Node.js and PhantomJS.
  - "if [ $ISTANBUL = false ]; then\n  node ./node_modules/lodash-cli/bin/lodash -o
    ./dist/lodash.js\n  node ./node_modules/lodash-cli/bin/lodash modularize exports=node
    -o ./\n  node ./node_modules/lodash-cli/bin/lodash -d -o ./lodash.js\n  if [ $SAUCE_LABS
    = false ]; then\n    cd ./test\n    $BIN $OPTION ./test.js ../lodash.js\n    if
    [ $TRAVIS_SECURE_ENV_VARS = true ]; then\n      $BIN $OPTION ./test.js ../dist/lodash.min.js\n\
    \    fi\n  fi\nfi\n"
  # Test in Sauce Labs.
  - "if [ $SAUCE_LABS = true ]; then\n  node ./node_modules/lodash-cli/bin/lodash
    core -o ./dist/lodash.core.js\n  npm run build\n  $BIN ./test/saucelabs.js name=\"\
    lodash tests\"     runner=\"test/index.html?build=../dist/lodash.js&noglobals=true\"\
    \     tags=development\n  $BIN ./test/saucelabs.js name=\"lodash tests\"     runner=\"\
    test/index.html?build=../dist/lodash.min.js&noglobals=true\" tags=production\n\
    \  $BIN ./test/saucelabs.js name=\"lodash-fp tests\"  runner=\"test/fp.html?noglobals=true\"\
    \                                tags=development\n  $BIN ./test/saucelabs.js
    name=\"underscore tests\" runner=\"test/underscore.html?build=../dist/lodash.js\"\
    \               tags=development,underscore\n  $BIN ./test/saucelabs.js name=\"\
    underscore tests\" runner=\"test/underscore.html?build=../dist/lodash.min.js\"\
    \           tags=production,underscore\n  $BIN ./test/saucelabs.js name=\"backbone
    tests\"   runner=\"test/backbone.html?build=../dist/lodash.js\"              \
    \   tags=development,backbone\n  $BIN ./test/saucelabs.js name=\"backbone tests\"\
    \   runner=\"test/backbone.html?build=../dist/lodash.min.js\"             tags=production,backbone\n\
    \  $BIN ./test/saucelabs.js name=\"backbone tests\"   runner=\"test/backbone.html?build=../dist/lodash.core.js\"\
    \            tags=development,backbone\n  $BIN ./test/saucelabs.js name=\"backbone
    tests\"   runner=\"test/backbone.html?build=../dist/lodash.core.min.js\"     \
    \   tags=production,backbone\nfi\n"
dist: trusty
